# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Shuffle
version:      0.02
version_from: lib/Template/Plugin/Shuffle.pm
installdirs:  site
requires:
    Algorithm::Numerical::Shuffle: 1.4
    Template:                      2.08
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
